# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


INFO_TEXT = """
Доступные математические функции: \n 
+, -, *, /, ^, \n
sin, cos, tan, cot, log, ln, exp и унарный минус.\n
Ошибки: \n0 - успешно, \t   1 - превышено кол-во операций, \n2 - деление на 0, \t   3 - вне отрезка"""


class InfoUI(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setObjectName("MainWindow")
        self.resize(513, 500)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 481, 480))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Name = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.verticalLayout.addWidget(self.Name)
        self.sepLine2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.sepLine2.setFrameShape(QtWidgets.QFrame.HLine)
        self.sepLine2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sepLine2.setObjectName("sepLine2")
        self.verticalLayout.addWidget(self.sepLine2)
        self.Author = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Author.setObjectName("Author")
        self.verticalLayout.addWidget(self.Author)
        self.Variant = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Variant.setObjectName("Variant")
        self.verticalLayout.addWidget(self.Variant)
        self.sepLine1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.sepLine1.setFrameShape(QtWidgets.QFrame.HLine)
        self.sepLine1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sepLine1.setObjectName("sepLine1")
        self.verticalLayout.addWidget(self.sepLine1)
        self.Functions = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Functions.setObjectName("Functions")
        self.verticalLayout.addWidget(self.Functions)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name.setText(_translate("MainWindow", 'ЛР 2 \n“Методы уточнения корней"'))
        self.Author.setText(_translate("MainWindow", "Автор: Евграфов Фёдор ИУ7-25Б"))
        self.Variant.setText(_translate("MainWindow", "Вариант - 8"))
        self.Functions.setText(_translate("MainWindow", INFO_TEXT))
